import Foundation

/// Exporter responsible for serializing `DiffResult` into JSON, Markdown, and HTML format.
public struct ReportExporter: Sendable {
    public init() {}
    
    /// Exports `DiffResult` as raw formatted JSON Data.
    public func exportJSON(result: DiffResult) throws -> Data {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        return try encoder.encode(result)
    }
    
    /// Exports `DiffResult` as formatted Markdown string (suitable for PR comments and issue trackers).
    public func exportMarkdown(result: DiffResult) -> String {
        var md = "# 🔍 DesignLens Comparison Report\n\n"
        
        let criticalCount = result.diffItems.filter { $0.severity == .critical }.count
        let warningCount = result.diffItems.filter { $0.severity == .warning }.count
        let infoCount = result.diffItems.filter { $0.severity == .info }.count
        
        md += "## Executive Summary\n"
        md += "- **Overall Design Match**: `\(String(format: "%.1f", result.matchPercentage))%`\n"
        md += "- **Reference Canvas Size**: `\(Int(result.referenceImageSize.width))x\(Int(result.referenceImageSize.height))px`\n"
        md += "- **Actual Canvas Size**: `\(Int(result.actualImageSize.width))x\(Int(result.actualImageSize.height))px`\n"
        md += "- **Total Elements Analyzed**: `\(result.totalBlocksDetected)`\n"
        md += "- **Total Discrepancies Found**: `\(result.diffItems.count)` (`\(criticalCount)` Critical, `\(warningCount)` Warning, `\(infoCount)` Info)\n\n"
        
        if result.diffItems.isEmpty {
            md += "✅ **No visual or layout discrepancies detected! Design matches specification.**\n"
            return md
        }
        
        md += "## Detected Discrepancies\n\n"
        md += "| Severity | Category | Element | Issue Description | Reference | Actual |\n"
        md += "| :--- | :--- | :--- | :--- | :--- | :--- |\n"
        
        for item in result.diffItems {
            let severityBadge: String
            switch item.severity {
            case .critical: severityBadge = "🔴 Critical"
            case .warning:  severityBadge = "🟡 Warning"
            case .info:     severityBadge = "🔵 Info"
            }
            
            let elementName = item.elementName.replacingOccurrences(of: "|", with: "\\|")
            let title = item.title.replacingOccurrences(of: "|", with: "\\|")
            let refVal = item.referenceValue.replacingOccurrences(of: "|", with: "\\|")
            let actVal = item.actualValue.replacingOccurrences(of: "|", with: "\\|")
            
            md += "| \(severityBadge) | \(item.category.rawValue) | `\(elementName)` | \(title) | `\(refVal)` | `\(actVal)` |\n"
        }
        
        md += "\n---\n*Report generated by DesignLens 2.0 Engine*\n"
        return md
    }
    
    /// Exports `DiffResult` as self-contained interactive Dark Glass HTML document.
    public func exportHTML(result: DiffResult) -> String {
        let criticalCount = result.diffItems.filter { $0.severity == .critical }.count
        let warningCount = result.diffItems.filter { $0.severity == .warning }.count
        let infoCount = result.diffItems.filter { $0.severity == .info }.count
        let matchScoreFormatted = String(format: "%.1f", result.matchPercentage)
        
        let scoreColor: String
        if result.matchPercentage >= 90.0 {
            scoreColor = "#10B981"
        } else if result.matchPercentage >= 75.0 {
            scoreColor = "#F59E0B"
        } else {
            scoreColor = "#EF4444"
        }
        
        var rowsHTML = ""
        for (idx, item) in result.diffItems.enumerated() {
            let severityColor: String
            let severityLabel: String
            switch item.severity {
            case .critical:
                severityColor = "#EF4444"
                severityLabel = "Critical"
            case .warning:
                severityColor = "#F59E0B"
                severityLabel = "Warning"
            case .info:
                severityColor = "#3B82F6"
                severityLabel = "Info"
            }
            
            let bgClass = idx % 2 == 0 ? "rgba(255,255,255,0.02)" : "transparent"
            
            rowsHTML += """
            <tr style="background-color: \(bgClass); border-bottom: 1px solid rgba(255,255,255,0.06);">
                <td style="padding: 12px; font-weight: 600;">
                    <span style="display: inline-block; padding: 3px 8px; border-radius: 4px; background-color: \(severityColor)22; color: \(severityColor); border: 1px solid \(severityColor)44; font-size: 11px;">
                        \(severityLabel)
                    </span>
                </td>
                <td style="padding: 12px; color: #94A3B8; font-size: 12px;">\(item.category.rawValue)</td>
                <td style="padding: 12px; font-family: monospace; font-size: 12px; color: #F8FAFC;">\(escapeHTML(item.elementName))</td>
                <td style="padding: 12px; color: #E2E8F0;">
                    <div style="font-weight: 500;">\(escapeHTML(item.title))</div>
                    <div style="font-size: 11px; color: #94A3B8; margin-top: 2px;">\(escapeHTML(item.issueDescription))</div>
                </td>
                <td style="padding: 12px; font-family: monospace; font-size: 12px; color: #A7F3D0;">\(escapeHTML(item.referenceValue))</td>
                <td style="padding: 12px; font-family: monospace; font-size: 12px; color: #FECACA;">\(escapeHTML(item.actualValue))</td>
            </tr>
            """
        }
        
        return """
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>DesignLens Comparison Report</title>
            <style>
                body {
                    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
                    background-color: #0F172A;
                    color: #F8FAFC;
                    margin: 0;
                    padding: 32px;
                    line-height: 1.5;
                }
                .container {
                    max-width: 1100px;
                    margin: 0 auto;
                }
                .header {
                    display: flex;
                    justify-content: space-between;
                    align-items: center;
                    background: rgba(30, 41, 59, 0.7);
                    backdrop-filter: blur(12px);
                    border: 1px solid rgba(255, 255, 255, 0.1);
                    border-radius: 12px;
                    padding: 24px 32px;
                    margin-bottom: 24px;
                }
                .title-area h1 {
                    margin: 0 0 4px 0;
                    font-size: 24px;
                    font-weight: 700;
                    color: #38BDF8;
                }
                .title-area p {
                    margin: 0;
                    font-size: 13px;
                    color: #94A3B8;
                }
                .score-badge {
                    text-align: right;
                }
                .score-number {
                    font-size: 36px;
                    font-weight: 800;
                    color: \(scoreColor);
                }
                .score-label {
                    font-size: 11px;
                    text-transform: uppercase;
                    letter-spacing: 1px;
                    color: #94A3B8;
                }
                .grid {
                    display: grid;
                    grid-template-columns: repeat(4, 1fr);
                    gap: 16px;
                    margin-bottom: 24px;
                }
                .card {
                    background: rgba(30, 41, 59, 0.5);
                    border: 1px solid rgba(255, 255, 255, 0.08);
                    border-radius: 10px;
                    padding: 16px;
                    text-align: center;
                }
                .card-val {
                    font-size: 22px;
                    font-weight: 700;
                    margin-top: 4px;
                }
                .card-lbl {
                    font-size: 12px;
                    color: #94A3B8;
                }
                .table-card {
                    background: rgba(30, 41, 59, 0.6);
                    border: 1px solid rgba(255, 255, 255, 0.1);
                    border-radius: 12px;
                    overflow: hidden;
                }
                table {
                    width: 100%;
                    border-collapse: collapse;
                    text-align: left;
                }
                th {
                    background: rgba(15, 23, 42, 0.6);
                    padding: 14px 12px;
                    font-size: 11px;
                    text-transform: uppercase;
                    letter-spacing: 0.8px;
                    color: #94A3B8;
                    border-bottom: 1px solid rgba(255, 255, 255, 0.1);
                }
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <div class="title-area">
                        <h1>🔍 DesignLens Report</h1>
                        <p>UI & Visual Layout Discrepancy Analysis</p>
                    </div>
                    <div class="score-badge">
                        <div class="score-number">\(matchScoreFormatted)%</div>
                        <div class="score-label">Overall Match Score</div>
                    </div>
                </div>
                
                <div class="grid">
                    <div class="card">
                        <div class="card-lbl">Analyzed Elements</div>
                        <div class="card-val" style="color: #38BDF8;">\(result.totalBlocksDetected)</div>
                    </div>
                    <div class="card">
                        <div class="card-lbl">Critical Issues</div>
                        <div class="card-val" style="color: #EF4444;">\(criticalCount)</div>
                    </div>
                    <div class="card">
                        <div class="card-lbl">Warnings</div>
                        <div class="card-val" style="color: #F59E0B;">\(warningCount)</div>
                    </div>
                    <div class="card">
                        <div class="card-lbl">Info / Extras</div>
                        <div class="card-val" style="color: #3B82F6;">\(infoCount)</div>
                    </div>
                </div>
                
                <div class="table-card">
                    <table>
                        <thead>
                            <tr>
                                <th>Severity</th>
                                <th>Category</th>
                                <th>Element</th>
                                <th>Description</th>
                                <th>Reference Spec</th>
                                <th>Actual Implementation</th>
                            </tr>
                        </thead>
                        <tbody>
                            \(rowsHTML.isEmpty ? "<tr><td colspan='6' style='padding: 32px; text-align: center; color: #10B981;'>✅ Perfect Match - No Discrepancies Found</td></tr>" : rowsHTML)
                        </tbody>
                    </table>
                </div>
            </div>
        </body>
        </html>
        """
    }
    
    private func escapeHTML(_ input: String) -> String {
        input.replacingOccurrences(of: "&", with: "&amp;")
             .replacingOccurrences(of: "<", with: "&lt;")
             .replacingOccurrences(of: ">", with: "&gt;")
             .replacingOccurrences(of: "\"", with: "&quot;")
    }
}
